version: "3.9"
services:
  spark-master:
    image: spark-test-master
    container_name: spark-master
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - /home/kola/Downloads/spark-3.1.1-bin-hadoop3.2:/opt/spark
  spark-worker:
    image: spark-test-worker
    depends_on:
      - spark-master
    volumes:
      - /home/kola/Downloads/spark-3.1.1-bin-hadoop3.2:/opt/spark
    ports:
      - "8082:8081"
      - "4040:4040"
    command: spark-master:7077
    restart: on-failure
